### PR TITLE
#42 Fixed too much maker notes entries on panasonic

### PR DESCRIPTION
**Pull request by vojtatranta**
#42
The number of entries here was like 1644.
Problem is that it is not async, so it just cause memory leak :(.
So i fixed it simply like this, I am sure you'll find better way :)

Thank you for this exif reader, great thing, I would be screwed without. I owe you a beer:)

### CODE REVIEW

**Comment by Sitebase** [comment]
@vojtatranta my PR already fixed this https://github.com/gomfunkel/node-exif/pull/38

**Comment by oeuillot** [comment]
Fixed by version 0.5.0
https://github.com/gomfunkel/node-exif/releases/tag/0.5.0

**Comment by vojtatranta** [comment]
@Sitebase do you want me to confirm it?

**Comment by oeuillot** [comment]
yes please :-)

2016-01-20 17:24 GMT+01:00 vojtatranta <notifications@github.com>:

**Pull request closed without merging**
